package:
  name: matlab_kernel
  version: "0.6.9"

source:
  fn: matlab_kernel-0.6.9.tar.gz
  url: https://pypi.python.org/packages/source/m/matlab_kernel/matlab_kernel-0.6.9.tar.gz
  md5: 8b49eda9e7f97e70bb8aee0bb2f40da6
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - matlab_kernel = matlab_kernel:main
    #
    # Would create an entry point called matlab_kernel that calls matlab_kernel.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - metakernel >=0.10.5
    - pymatbridge
    - ipython >=3.0
    - ipykernel

  run:
    - python
    - metakernel >=0.10.5
    - pymatbridge
    - ipython >=3.0

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/calysto/matlab_kernel
  license: BSD License
  summary: 'A Matlab kernel for Jupyter/IPython'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
