package:
  name: gpy
  version: "1.0.9"

source:
  fn: GPy-1.0.9.tar.gz
  url: https://pypi.python.org/packages/98/46/3f9f794efada276d4041863a966a50dcd5a205d181eff0f4d5a8d6ba905e/GPy-1.0.9.tar.gz
  md5: 87a8db7dd24e808926908bb5b73f88ce
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gpy = gpy:main
    #
    # Would create an entry point called gpy that calls gpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - scipy >=0.16
    - six
    - paramz >=0.5.2

  run:
    - python
    - numpy >=1.7
    - scipy >=0.16
    - six
    - paramz >=0.5.2

test:
  # Python imports
  imports:
    - GPy
    - GPy.core
    - GPy.core.parameterization
    - GPy.examples
    - GPy.inference
    - GPy.inference.latent_function_inference
    - GPy.inference.mcmc
    - GPy.inference.optimization
    - GPy.kern
    - GPy.kern.src
    - GPy.kern.src.psi_comp
    - GPy.likelihoods
    - GPy.mappings
    - GPy.models
    - GPy.plotting
    - GPy.plotting.gpy_plot
    - GPy.plotting.matplot_dep
    - GPy.plotting.matplot_dep.controllers
    - GPy.plotting.plotly_dep
    - GPy.testing
    - GPy.util

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    # - nose
    - matplotlib

about:
  home: http://sheffieldml.github.com/GPy/
  license: BSD License
  summary: 'The Gaussian Process Toolbox'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
