package:
  name: pymatbridge
  version: "0.5.2"

source:
  fn: pymatbridge-0.5.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pymatbridge/pymatbridge-0.5.2.tar.gz
  md5: a3a75cd4b504f8f7c5c181bcf0366dd4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - metakernel = metakernel:main
    #
    # Would create an entry point called metakernel that calls metakernel.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - ipython >=3.0
    - pyzmq
    - numpy

  run:
    - python
    - ipython >=3.0
    - pyzmq
    - numpy

test:
  # Python imports
  imports:
    - pymatbridge

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/arokem/python-matlab-bridge
  license:
  summary: Python-MATLAB(R) Bridge and IPython matlab magic

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
